version: 2
jobs:
  build:
    docker:
      - image: alpine:latest
    
    working_directory: ~/johejo-web

    steps:
      - checkout
      - run:
          name: Install Hugo
          environment:
            HUGO_VERSION: 0.47.1
          command: |
            apk add --no-cache curl tar
            curl -sL https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz | tar zx
      - run:
          name: Build sites
          command: ./hugo

  deploy:
    docker:
      - image: microsoft/azure-cli
    working_directory: /tmp/johejo-web
    steps:
      - run:
          name: Deploy to Azure Blob
          command: az storage blob upload-batch -d \$web -s ./public/

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
